# Generated by Django 4.2.5 on 2023-09-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(default=0)),
                ('nationality', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('tribe', models.CharField(max_length=20)),
            ],
        ),
    ]
