# Generated by Django 4.2.5 on 2023-09-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0003_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
