# Generated by Django 4.2.3 on 2023-09-18 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_data_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
