# Generated by Django 4.2.3 on 2023-09-27 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0011_alter_data_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
