# Generated by Django 4.2.3 on 2023-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0012_alter_data_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
